export const POST_COMMENT_REPLY_REQUEST = 'POST_COMMENT_REPLY_REQUEST';
export const POST_COMMENT_REPLY_SUCCESS = 'POST_COMMENT_REPLY_SUCCESS';
export const POST_COMMENT_REPLY_FAILURE = 'POST_COMMENT_REPLY_FAILURE';